enum PlaceFilters {
  PLACE_TYPES, PLACE_PRIORITY_REGIMES, PLACE_LOCALISATIONS
}

enum PlaceTypes {
  LONGITUDINAL, EPI, BATAILLE
}

enum PlacePriorityRegimes {
  LIVRAISON, DEUX_ROUES, PAYANT_MIXTE, PAYANT_ROTATIF, ELECTRIQUE, GIG_GIC, AUTRE_REGIME, GRATUIT, LOCATION
}

enum PlaceLocalisations {
  CHAUSSEE, LINCOLN, CONTRE_TERRE_PLEIN, CONTRE_ALLEE, TERRE_PLEIN, FAUX_LINCOLN, TROTTOIR
}